### ISSUE TITLE
Projectile does not move

### ISSUE THREAD

**Issue by Cromewell** [opensourcegamedev/SpaceChaos#21]
If the player is standing, the projectile won't move.
Because we're using the player moveDirVec at the moment to set the projectile moveDirVec.

**Comment by JuKu** [comment]
Maybe it will be an good idea to dont use players move direction if he isnt moving and use the angle or front vectoir instead, provided by **MouseDependentMovementComponent** in method getFrontVec().

**Comment by JuKu** [comment]
@Cromewell I have solved this problem.
