### ISSUE TITLE
Adjust projectile spawning

### ISSUE THREAD

**Issue by Cromewell** [opensourcegamedev/SpaceChaos#22]
The projectile does not spawn at the canons of the shuttle.

**Comment by JuKu** [comment]
Currently, if the player shoot an projectile, the projectile doesnt start on front of shuttle, it starts on right of player.

![sl](https://cloud.githubusercontent.com/assets/1138046/24977335/fdb1cc0e-1fcc-11e7-82de-9777f90b24ec.PNG)

In German:
Wenn man ein Projektile verschießt, kommt dies nicht "aus der Spitze", sondern irgendwo an der Seite raus. Quasi startet des Projektile nicht vorne zentriert, sondern irgendwo neben dem Spieler.

**Comment by JuKu** [comment]
Also if you flying backwards, projectile also flys backwards.

![fn](https://cloud.githubusercontent.com/assets/1138046/24980772/f2713db8-1fd9-11e7-938a-a7a9b98cbb75.PNG)

**Comment by JuKu** [comment]
German:
Oder man lässt das Projektil abwechselnd aus der linken und rechten Kanone starten.
