### ISSUE TITLE
Enemy hpreduce bug

### ISSUE THREAD

**Issue by Cromewell** [opensourcegamedev/SpaceChaos#28]
After colliding with an enemy: If the player stays on enemy front (close to leave colliding circle), the enemy hps are getting reduced.

**Comment by JuKu** [comment]
Can you explain it an little bit specificer?
What do i have to do, to reproduce this bug?

I fly into an enemy shuttle, the HP of player and enemy shuttle will be reduced.
What have i do after this step?

**Comment by JuKu** [comment]
I have moved this issue to 2. Pre-Alpha.

**Comment by JuKu** [comment]
@Cromewell I cannot reproiduce this bug.
Please write more details in this issue!
