### ISSUE TITLE
Create Steam Account for Steam Greenlight

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#42]
To provide steam access to SpaceChaos, we have to create an steam account and provide this game on steam greenlight.

**Comment by crykn** [comment]
Steam Greenlight will be replaced by Steam Direct in Spring 2017.

**Comment by JuKu** [comment]
@crykn We know. Because we dont want to pay 5.000 USD (Steam Direct), we want to try to get this game in steam store with steam greenlight.

**Comment by crykn** [comment]
Are you sure you can get the game in the store in time? Because in the current state you'll never get enough votes for that. 
Also, the exact price wasn't announced as of now.

**Comment by JuKu** [comment]
@crykn We dont know. Let us discuss this in slack, please.
