### ISSUE TITLE
Balance game mechanics

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#59]
We have to balance game mechanics, attack / fighting system & AI.
For this issue we will need help from an **external game designer**, so this isnt an internal issue!

**Comment by JuKu** [comment]
I have assigned me (but i dont want to close this issue), so noone else can assign it.
This issue will be closed by an external game designer.

**Comment by adrian-bu** [comment]
@JuKu would you like to check whether we need to better balance the game mechanics anymore?

**Comment by JuKu** [comment]
@adrian-bu Okay.
But its better, if we check this together.

**Comment by adrian-bu** [comment]
I'm convinced that the game-balancing is well enough for the moment.
