### ISSUE TITLE
Collision Detection / Movement in AI

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#64]
Collision Detection / Movement in AI

![mt](https://user-images.githubusercontent.com/1138046/29224989-e9309d78-7ecc-11e7-9b16-e674aaedad6c.png)

![mt22](https://user-images.githubusercontent.com/1138046/29224994-ed8b37ac-7ecc-11e7-81b6-97a7f90357c3.png)

**Comment by JuKu** [comment]
@adrian-bu Is there an new progress or state?

**Comment by adrian-bu** [comment]
Of course, but i'm not sure whether we need this anymore.

**Comment by JuKu** [comment]
@adrian-bu Maybe its better, if we close this issue?

**Comment by adrian-bu** [comment]
I agree with you
