### ISSUE TITLE
Improve shield effect game mechanics

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#67]
Shield should not be removed, if projectiles collides with shield / player. They should only reduce HP, if player collides with meteorits or by timer.

**Comment by adrian-bu** [comment]
Shield also reduces energy by colliding with powerups at the moment.

**Comment by crykn** [comment]
I reversed the proposed mechanics: shields block _only_ the damage done by projectiles and not the one done by meteorites.

**Comment by JuKu** [comment]
nice! :D
