### ISSUE TITLE
Score List

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#68]
It will be nice, if player see's an score list (maybe with pewn.de synchronisation, see #45 ?) so he is more motivated to reach an higher score and plays the game an longer time.

**Comment by adrian-bu** [comment]
I am convinced it is more important to improve the score system first. After this we should be thinking about synchronisation

**Comment by JuKu** [comment]
@adrian-bu Should we improve Score system yet?

**Comment by adrian-bu** [comment]
Maybe we don't need to improve our Score system. It would be great if different kind of enemies create different score points

**Comment by adrian-bu** [comment]
Done

**Comment by JuKu** [comment]
@adrian-bu nice! :D 
Good job!
