### ISSUE TITLE
Bug: enemys can destroy torpedos with normal shoots

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos#70]
If player shoots an torpedo, enemys can destroy this torpedos with normal shoots.

**Comment by adrian-bu** [comment]
A torpedo should possess some kind of health component to resist at least one shot.

**Comment by JuKu** [comment]
@adrian-bu Maybe an torpedo should be resistant against all shots, than he dont needs an health component.

**Comment by adrian-bu** [comment]
I entirely share your view. That's a great suggestion.

**Comment by crykn** [comment]
Fixed.

**Comment by JuKu** [comment]
👍
