### ISSUE TITLE
Bug: We should improve the creation of enemies and powerups

### ISSUE THREAD

**Issue by adrian-bu** [opensourcegamedev/SpaceChaos#75]
Sometimes a wall of enemies appears at the beginning or ending of the game.
The amount of power ups increases, if the player is moving (or collecting the power ups).
See also #74 .
Either the player dies or the game crashes (because of the amount of enemies and power ups) at the end of the game.

**Comment by adrian-bu** [comment]
![enemies](https://user-images.githubusercontent.com/29602034/29367053-f8bfe370-829b-11e7-9d78-eae9b3cef054.PNG)
![power ups](https://user-images.githubusercontent.com/29602034/29367054-f8c6c8ac-829b-11e7-821f-cd756dd586dc.PNG)

**Comment by JuKu** [comment]
@adrian-bu WTF? :D 
Wie hast du diese rekordverdächtige Zeit erreicht? :D

**Comment by adrian-bu** [comment]
Ab der - geschätzt - 2. Minute kann man nicht mehr von den gegnerischen Raumschiffen getötet werden, sofern man etwas bei der Sache ist. Man muss nur aufpassen, dass das Spiel nicht abstürzt (man kann sich ja, wie im Bild zu sehen, hinter den Powerups verstecken) :)

**Comment by JuKu** [comment]
@adrian-bu Was meinst du damit: "aufpassen, dass das Spiel nicht abstürzt"?
Ist es denn schon einmal abgestürzt? Wie ist das passiert?

Erscheint logisch, denn nach 2 Minuten sind wohl so viele Power Ups im Spiel...

**Comment by adrian-bu** [comment]
Wenn du dich kaum vom Fleck bewegst, respawnen die Powerups auch nicht in allzu großer Menge
Bewegst du dich allerdings ab - wieder geschätzt - Minute 3 monoton in eine Richtung, stürzt entweder das Spiel ab, oder du gelangst wieder ins Hauptmenü

**Comment by JuKu** [comment]
@adrian-bu 
Oh...
Das wusste ich noch gar nicht!

Ist das Problem gelöst, weil du das Issue geschlossen hast?

**Comment by adrian-bu** [comment]
Habe das Issue geschlossen, weil das Problem größtenteils behoben wurde: Das Spawnen funktioniert, nach mehrmaligem Testen, problemlos. Selbst die Wand aus Gegnern am Anfang des Spiels musste ich nicht mehr erleben

**Comment by JuKu** [comment]
@adrian-bu Sehr gut! :D 
Danke! :D
